version: "3.9"

x-common-config: &common-config
  OZONE-SITE.XML_ozone.metadata.dirs: /data/metadata
  OZONE-SITE.XML_ozone.scm.datanode.id.dir: /data/datanode
  OZONE-SITE.XML_ozone.om.metadata.dirs: /data/metadata/om
  OZONE-SITE.XML_ozone.scm.metadata.dirs: /data/metadata/scm
  OZONE-SITE.XML_hdds.datanode.dir: /data/hdds
  OZONE-SITE.XML_ozone.recon.db.dir: /data/recon

x-image: &image
  image: apache/ozone:latest
  volumes:
    - ozone-data:/data
  networks:
    - swarm-net

services:
  om:
    <<: *image
    ports:
      - 9874:9874
      - 9862:9862
    environment:
      <<: *common-config
      ENSURE_OM_INITIALIZED: /data/metadata/om/current/VERSION
      CORE-SITE.XML_hadoop.proxyuser.hadoop.hosts: "*"
      CORE-SITE.XML_hadoop.proxyuser.hdoop.groups: "*"
    command: ["ozone", "om"]

  scm:
    <<: *image
    ports:
      - 9876:9876
    environment:
      <<: *common-config
      ENSURE_SCM_INITIALIZED: /data/metadata/scm/current/VERSION
    command: ["ozone", "scm"]

  recon:
    <<: *image
    ports:
      - 9888:9888
    environment:
      <<: *common-config
    command: ["ozone", "recon"]

  s3g:
    <<: *image
    ports:
      - 9878:9878
    secrets:
      - global-access-key
      - global-secret-key
    environment:
      <<: *common-config
      OZONE-SITE.XML_ozone.s3g.authentication.type: SIMPLE
      OZONE-SITE.XML_ozone.s3g.awsAccessKeyId: "/run/secrets/global-access-key"
      OZONE-SITE.XML_ozone.s3g.awsSecretAccessKey: "/run/secrets/global-secret-key"
    command: ["ozone", "s3g"]

  httpsf:
    <<: *image
    ports:
      - 14000:14000
    environment:
      <<: *common-config
      CORE-SITE.XML_fs.defaultFS: "ofs://om"
    command: ["ozone", "httpsf"]

volumes:
  ozone-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.0.5,nolock,soft,rw
      device: ":/exports/ozone-data"

networks:
  swarm-net:
    external: true

secrets:
  global-access-key:
    external: true
  global-secret-key:
    external: true

